# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161116_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='blarg@blarg.com', max_length=200),
            preserve_default=False,
        ),
    ]
